/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import Clases.Cls_OrdenTrabajo;
import Clases.Cls_Salida;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPRow;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPTableHeader;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
//import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;

/**
 *
 * @author willi
 */
public class Frm_BuscarOrdenDeTrabajo extends javax.swing.JInternalFrame {
    private final Cls_OrdenTrabajo clsOrdenTrabajo;
    private Cls_Salida clsSalida;
    TableColumnModel columnModel;
    DefaultTableModel tableModel;
    String nroOrden = "";
    public static int enviar = 0;
    int num = 0;
    Frm_OrdenDeTrabajo1 formularioAgregar = new Frm_OrdenDeTrabajo1();

    ArrayList<Object[]> listaDeSalidas = new ArrayList<Object[]>();

    /**
     * Creates new form Frm_BuscarOrdenDeTrabajo
     */
    public Frm_BuscarOrdenDeTrabajo() {
        initComponents();
        clsOrdenTrabajo = new Cls_OrdenTrabajo();
        clsSalida = new Cls_Salida();
        listar();
    }
    
    private void listar(){
        jbt_index_ordenes.setModel(clsOrdenTrabajo.getDatosOrdenDeTrabajo());
    }
    
    private void verSalidasDeOrdenDeTrabajo(String nroOrden){
        jbt_show_orden.setModel(clsOrdenTrabajo.showOrdenTrabajo(nroOrden));
    }
    
    private void eidtarOrdenDeTrabajo(){
        ArrayList<Object[]> orden = new ArrayList<>();
        int cantFilas = jbt_show_orden.getRowCount();
        int cantColumnas = jbt_show_orden.getColumnCount();
        for(int fila = 0; fila < cantFilas; fila++ ){
            Object[] salida = new Object[4];
            for(int colum = 0; colum < cantColumnas; colum++ ){
//                salida[colum] = null;
                salida[colum] = jbt_show_orden.getValueAt(fila, colum);
            }
            orden.add(salida);
        }
        Frm_Principal.contenedor.add(formularioAgregar);
        formularioAgregar.show();
        formularioAgregar.editarOrden(orden, this.nroOrden);
    }

    public void buscarOrdenDeTrabajo(String buscar){
        jbt_index_ordenes.setModel(clsOrdenTrabajo.buscarOrdenDeTrabajo(buscar));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jbt_index_ordenes = new javax.swing.JTable();
        btn_buscar_orden = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_buscar_orden = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jbt_show_orden = new javax.swing.JTable();
        btn_nuevaOrdenTrabajo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Buscar Orden de Trabajo");
        setPreferredSize(new java.awt.Dimension(1041, 546));

        jbt_index_ordenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nota", "Opciones"
            }
        ));
        jbt_index_ordenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_index_ordenesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jbt_index_ordenes);

        btn_buscar_orden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_consultas.png"))); // NOI18N
        btn_buscar_orden.setText("Buscar Orden");
        btn_buscar_orden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_ordenActionPerformed(evt);
            }
        });
        btn_buscar_orden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_buscar_ordenKeyReleased(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imprimir.png"))); // NOI18N
        jButton2.setText("Imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txt_buscar_orden.setToolTipText("Ingrese el numero de orden");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_modificar.png"))); // NOI18N
        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jbt_show_orden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nro Factura", "Cod. Pproducto", "Cantidad", "Fecha"
            }
        ));
        jScrollPane2.setViewportView(jbt_show_orden);

        btn_nuevaOrdenTrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_nuevo.png"))); // NOI18N
        btn_nuevaOrdenTrabajo.setText("Nueva Orden");
        btn_nuevaOrdenTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevaOrdenTrabajoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Orden de trabajo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel2.setText("Lista y detalle de las ordenes de trabajo ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_nuevaOrdenTrabajo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_buscar_orden, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_buscar_orden)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_buscar_orden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_buscar_orden))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_nuevaOrdenTrabajo))
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscar_ordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_ordenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscar_ordenActionPerformed

    /**
     * Imprimir Orden de Trabajo
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Document documento = new Document();
        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, 
                new FileOutputStream(ruta + "/Documents/OrdenDeTrabajo"+this.nroOrden+".pdf"));
            com.itextpdf.text.Image header = com.itextpdf.text.Image.getInstance("src/Imagenes/logoEmp.jpeg");
            header.scaleToFit(150,100);
            header.setAlignment(Chunk.ALIGN_CENTER);
            
            Paragraph parrafo = new Paragraph();
            parrafo.setAlignment(Chunk.ALIGN_CENTER);
            parrafo.add("Orden de Trabajo \n \n");
            parrafo.setFont(FontFactory.getFont("Tahoma", 14, Font.BOLD, BaseColor.DARK_GRAY));
            
            documento.setPageSize(PageSize.LETTER);
            documento.open();
            documento.add(header);
            documento.add(parrafo);
            
            PdfPTable tablaShowOrden = new PdfPTable(4);

            PdfPTable encabezado = new PdfPTable(4);

            tablaShowOrden.addCell("Nro Factura");
            tablaShowOrden.addCell("Codigo del Producto");
            tablaShowOrden.addCell("Cantidad");
            tablaShowOrden.addCell("Fecha");
            
//            tablaShowOrden.setHeaderRows(encabezadoDeTabla);
            
            for(int fila = 0; fila < jbt_show_orden.getRowCount(); fila++){

                tablaShowOrden.addCell(String.valueOf(jbt_show_orden.getValueAt(fila, 0)));
                tablaShowOrden.addCell(String.valueOf(jbt_show_orden.getValueAt(fila, 1)));
                tablaShowOrden.addCell(String.valueOf(jbt_show_orden.getValueAt(fila, 2)));
                tablaShowOrden.addCell(String.valueOf(jbt_show_orden.getValueAt(fila, 3)));

                
            }
            documento.add(tablaShowOrden);
            documento.close();
            JOptionPane.showMessageDialog(null, "Documento generado exitosamente");
        
        } catch (DocumentException | IOException e) {
            JOptionPane.showMessageDialog(null, "El error es"+ e.getMessage());
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbt_index_ordenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_index_ordenesMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            int filaSeleccionada = jbt_index_ordenes.getSelectedRow();
            int columnaSelecciona = jbt_index_ordenes.getSelectedColumn();
            if( columnaSelecciona == 0 ){
                Object nroOrden = jbt_index_ordenes.getValueAt(filaSeleccionada, 0); //Devuelve un String
                this.nroOrden = nroOrden.toString();
                jbt_show_orden.setModel(clsOrdenTrabajo.showOrdenTrabajo((String)nroOrden));

            }            
        }
    }//GEN-LAST:event_jbt_index_ordenesMouseClicked

    private void btn_nuevaOrdenTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevaOrdenTrabajoActionPerformed
        // TODO add your handling code here:
        Frm_Principal.contenedor.add(formularioAgregar);
        formularioAgregar.show();
        
    }//GEN-LAST:event_btn_nuevaOrdenTrabajoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        eidtarOrdenDeTrabajo();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_buscar_ordenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_buscar_ordenKeyReleased
        // TODO add your handling code here:
        buscarOrdenDeTrabajo(txt_buscar_orden.getText());
    }//GEN-LAST:event_btn_buscar_ordenKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar_orden;
    private javax.swing.JButton btn_nuevaOrdenTrabajo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jbt_index_ordenes;
    private javax.swing.JTable jbt_show_orden;
    private javax.swing.JTextField txt_buscar_orden;
    // End of variables declaration//GEN-END:variables
}
